name: Print GitHub Actions Secret

on:
  push:
    branches:
      - main  # Change to your branch name

jobs:
  print_secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Secret
      run: |
        echo "Secret Value: ${{ secrets.USERNAME }}"
